---
- name: Linux Connectivity Test
  hosts: linux_hosts
  gather_facts: true
  tasks:
    - name: Ping Linux host
      ansible.builtin.ping:

    - name: Display Linux OS details
      ansible.builtin.debug:
        msg: >-
          SUCCESS: Connected to {{ inventory_hostname }}.
          OS family={{ ansible_facts['os_family'] }},
          Distribution={{ ansible_facts['distribution'] }},
          Version={{ ansible_facts['distribution_version'] }}.
