---
- name: Linux Connectivity Test
  hosts: linux_hosts
  gather_facts: true
  tasks:
    - name: Ping Linux host
      ansible.builtin.ping:
      register: ping_output  # This captures the "pong" response

    - name: Display Connectivity and OS details
      ansible.builtin.debug:
        msg: 
          - "ping: {{ ping_output.ping }}"  # This displays "pong"
          - "------------------------------------------------"
          - "SUCCESS: Connected to {{ inventory_hostname }}."
          - "OS family: {{ ansible_facts['os_family'] }}"
          - "Distribution: {{ ansible_facts['distribution'] }}"
          - "Version: {{ ansible_facts['distribution_version'] }}"
          - "------------------------------------------------"
